"""update

Revision ID: ea0f0721235c
Revises: fd0de4ac80d6
Create Date: 2025-07-07 12:38:24.302177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0f0721235c'
down_revision: Union[str, Sequence[str], None] = 'fd0de4ac80d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_order_product_uc', 'order_items', ['order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_product_uc', 'order_items', type_='unique')
    # ### end Alembic commands ###